config/routes.rb
Myfacebook::Application.routes.draw do

  match 'welcome', :to => 'welcome#index', 
        :as => :welcome_path, :via => [:get, :post]

  get "base/index"

  root :to => 'base#index'


  ## fb oauth callback
  match "oauth_redirect" => "facebook#redirect", :as => :oauth_redirect



end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :user_id,       :type => String
  field :oauth_token,   :type => String
  field :expires,       :type => String
  field :issues_at,     :type => String
  field :user
  field :registration
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/base_controller.rb
class BaseController < FacebookController
  def index
  end

end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  before_filter :set_oauth
  
  def redirect 
    if params[:code] && 
      (session[:access_token] = CGI::unescape(@oauth.get_access_token(params[:code]))).present?                                             
      redirect_to(root_path)
    else
      flash[:error] = "#{params['error']['type']}: #{params['error']['message']}"                                                                             
      redirect_to(root_path)
    end
  end

protected
  def get_app_token
    @app_token ||= begin 
      @oauth.get_app_access_token
      app_graph = Koala::Facebook::GraphAPI.new(@app_token)
    end
  end

  def current_user
    if @facebook_cookies
      @current_user ||= user_from_cookies
    elsif  session[:access_token]
      @current_user ||= user_from_session
    end
  end

  def user_from_cookies
    return unless @facebook_cookies
    user = User.find_or_initialize_by(:uid => @facebook_cookies['uid'])
    if user.update_attributes(:access_token => @facebook_cookies['access_token'])
      return user
    else
      flash[:error] = "Error creating user!"
      redirect_to(root_path)
    end
  end

  def user_from_session
    @current_user = User.find_or_initialize_by(:uid => @graph.get_object('me')['id'])
    if @current_user.update_attributes(:access_token => session[:access_token])
      return @current_user
    else
      flash[:error] = "Error creating user!"
      redirect_to(root_path)
    end
  end

  def set_graph
    @graph ||= begin
      Koala::Facebook::GraphAPI.new(@facebook_cookies['access_token']) unless @facebook_cookies.blank?
    end
  end

  def set_oauth
    @oauth ||= begin
      Koala::Facebook::OAuth.new(AppConfig.app_id, AppConfig.secret_key, AppConfig.callback_url)
    end
  end

  def parse_facebook_cookies
    @facebook_cookies ||= @auth.new.get_user_info_from_cookie(cookies)
  end

	def unpack_signed_request
		@signed_request = @oauth.parse_signed_request(params['signed_request']) unless params['signed_request'].nil?
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < FacebookController
  before_filter :unpack_signed_request
  def index
    @user = User.find_or_initialize_by(@signed_request) unless @signed_request.nil? 
    @user.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/base/index.html.haml
= render :partial => 'common/fb_controls'

= link_to 'auth', oauth_redirect_url
= link_to 'login', @oauth.url_for_oauth_code(:permissions => 'publish_stream')

%a#login.login{:href=>'#'}
  login
%a#logout.logout{:href => '#'}
  logout

app/views/common/_fb_controls.html.haml
//fb:login-button{:scope => 'publish_stream'}
  

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Sandbox
    <!--[if IE]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
    = csrf_meta_tag
    = stylesheet_link_tag :application
    = yield :styles
  %body
    %input#fb_app_id{:type => 'hidden', :value => AppConfig.app_id.to_s}
    #fb-root
    :javascript
      window.fbAsyncInit = function() {
       FB.init({
        appId  : "#{AppConfig.app_id}",
        status : true, // check login status
        cookie : true, // enable cookies to allow the server to access the session
        xfbml  : true, // parse XFBML
        oauth  : true // enable OAuth 2.0
      });
      };
      (function(d){
         var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
         js = d.createElement('script'); js.id = id; js.async = true;
         js.src = "//connect.facebook.net/en_US/all.js";
         d.getElementsByTagName('head')[0].appendChild(js);
       }(document));

    = yield
    = javascript_include_tag :application
    = yield :scripts

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml

= debug @user
= debug @signed_request